name: Unity

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync_solution:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2020.3.4f1-webgl-0.16
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - run: |
          echo "$UNITY_LICENSE" > .ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile .ulf || :
      - uses: actions/checkout@v2
      - run: unity-editor batchmode -nographics -logFile - -executeMethod UnityEditor.SyncVS.SyncSolution -projectPath . -quit
      - uses: actions/upload-artifact@v2
        with:
          name: sync_solution
          path: ClickSniper.sln

  build_webgl:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2020.3.4f1-webgl-0.16
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - run: |
          echo "$UNITY_LICENSE" > .ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile .ulf || :
      - uses: actions/checkout@v2
      - run: make UnityCommand=unity-editor
      - uses: actions/upload-artifact@v2
        with:
          name: webgl
          path: Build/Web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Build/Web
